language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - python setup.py install
  - pip install nose
# command to run tests
script:
  - nosetests -v idt_tests.py # or py.test for Python versions 3.5 and below