language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - python setup.py install
  - pip install nose coveralls
# command to run tests
script:
  - nosetests -v idt_tests.py --with-coverage
after_success: coveralls