language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - python setup.py install
  - pip install nosetests
# command to run tests
script:
  - nosetest -v idt_tests.py # or py.test for Python versions 3.5 and below